#!/bin/sh

# spams needs numpy to be installed already
# since staNMF pulls in spams we must install them both at the end.

pip install spams==2.6.1

pip install git+https://github.com/Yu-Group/staNMF.git@fb88aed
